name: my_doctor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.10+1
  go_router: ^5.0.5
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"

  image: assets/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
